name: Deployment to Azure

on:
  push:
    branches:
      - deploy

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Log in to Azure
      run: |
        az login --service-principal \
          --username ${{ secrets.AZURE_CLIENT_ID }} \
          --password ${{ secrets.AZURE_CLIENT_SECRET }} \
          --tenant ${{ secrets.AZURE_TENANT_ID }}

    - name: Set Azure Subscription
      run: az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Deploy to Azure App Service
      run: |
        az webapp up --name MyLibraryManagementAPI \
          --resource-group Software_Engineering \
          --sku F1 \
          --runtime "PYTHON:3.8"

    - name: Validate Deployment
      run: az webapp show --name MyLibraryManagementAPI --resource-group Software_Engineering

