name: Pre-Merge Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  validate-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest --disable-warnings

      - name: Lint code
        run: |
          flake8 . --max-line-length=88
